"""Export interface-independent API and agent contracts without DB/model/network calls."""

import argparse
import asyncio
import json
from pathlib import Path

from cortex_core.api import create_app
from cortex_core.interactions import catalog
from cortex_core.settings import Settings

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
app = create_app(
    Settings(
        database_url="postgresql+pg8000://unused",
        jwt_issuer="https://identity.invalid",
        jwks_url="https://identity.invalid/keys",
        model_provider="ollama",
        local_model=None,
    )
)
try:
    spec = app.openapi()
    inventory = catalog(spec)
    tools = [
        tool.model_dump(mode="json", exclude_none=True)
        for tool in asyncio.run(app.state.mcp.list_tools())
    ]
finally:
    app.state.db.dispose()

artifacts = {
    "packages/contracts/openapi.json": json.dumps(spec, ensure_ascii=False, indent=2) + "\n",
    "packages/contracts/interactions.json": json.dumps(inventory, ensure_ascii=False, indent=2)
    + "\n",
    "packages/contracts/mcp-tools.json": json.dumps({"tools": tools}, ensure_ascii=False, indent=2)
    + "\n",
}
lines = [
    "# Interaction reference",
    "",
    "Generated by `scripts/export_interactions.py`; do not edit manually.",
    "",
    "Every HTTP action has a stable operation ID, an example intent, role prerequisites and effects. Exact parameter, request and response schemas are in `packages/contracts/openapi.json`. Agent tool schemas are in `packages/contracts/mcp-tools.json`. Listed roles are necessary prerequisites, not object access grants. The authenticated caller and current permissions remain authoritative.",
    "",
    "| Action | HTTP | Roles | Effect | Example intent |",
    "|---|---|---|---|---|",
]
for item in inventory["items"]:
    lines.append(
        f"| `{item['action_id']}` | `{item['method']} {item['path']}` | {', '.join(item['roles']) or 'public'} | {item['effect']} | {item['intent_example']} |"
    )
lines += ["", "## Agent tools", "", "| Tool | Effect hint | Description |", "|---|---|---|"]
for tool in tools:
    annotations = tool.get("annotations", {})
    lines.append(
        f"| `{tool['name']}` | {'read' if annotations.get('readOnlyHint') else 'writes state'} | {tool.get('description', '').replace(chr(10), ' ')} |"
    )
lines += [
    "",
    "Tool hints and confirmation metadata guide the host. They are not authentication, an approval receipt or enforcement of a user confirmation. See `docs/ai-native.md` for the host interaction protocol and current limits.",
    "",
]
artifacts["docs/interaction-reference.md"] = "\n".join(lines)
for name, content in artifacts.items():
    path = root / name
    if args.check:
        if not path.exists() or path.read_text() != content:
            raise SystemExit(
                f"Interaction contract drift: {name}; run scripts/export_interactions.py"
            )
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
print(f"{len(inventory['items'])} HTTP interactions and {len(tools)} MCP tools verified/exported")
